### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by dee-y** [igormironchik/security-cam#1]
Hello, i am a graphic designer. If you are interested, i can make a logo for your project for free. This will be my contribution to your project as open-source.

**Comment by igormironchik** [comment]
Hello, well, I don't have a big necessity in it. But why not, if your logo will be cool, why not. How did you find this project?

**Comment by dee-y** [comment]
I normally offer free logo designs to git repo owners in my free time. I check which repos are active, that's how i found yours.

**Comment by igormironchik** [comment]
Understood, thank you.

**Comment by dee-y** [comment]
Hello, here are logo proposals i have for you. Any choice? or improvements?

![security-cam-01](https://user-images.githubusercontent.com/36637989/46322769-abc69880-c5e2-11e8-9272-a86842cd45e7.png)

![securitycam2-01](https://user-images.githubusercontent.com/36637989/46322779-b3863d00-c5e2-11e8-98e9-9df3e59b0a1b.png)

**Comment by igormironchik** [comment]
I like it. Especially bottom ones. It's simple, but fully describes the application. Could you give me SVG version of your work, please?

**Comment by dee-y** [comment]
Alright am glad you found a pick. Can i make a pull request submitting files?

**Comment by dee-y** [comment]
Also are there any sizes you would like me to export for you?

**Comment by igormironchik** [comment]
In the SecurityCam/img folder you can find icon_NxN.png files. These files are icon of the application. Also I have SecurityCam/SecurityCam.ico file with all sizes in it. I'd like to have most left icon from the bottom row.

**Comment by igormironchik** [comment]
I told about black camera on white background with SecurityCam word. I'd like to see exactly this as icon of my application. You are a designer and should understand that this icon should have white background (rounded square?).

**Comment by dee-y** [comment]
Hi, just for clarity, this is the design elements you asked for...although i think the icon does better without the wordmark "SecurityCam" especially in consideration for icon smaller sizes as wordmark becomes unclear distorting logo. We could use logo with wordmark for the readme file since it doesnt need to be scaled down to small sizes while the one without wordmark as icon, good for scaling or what do you think?

![256px-01](https://user-images.githubusercontent.com/36637989/46462020-298fcd00-c7b8-11e8-91f4-bfa9f88ef125.png)

**Comment by dee-y** [comment]
more color schemes for bacground
![256px-02](https://user-images.githubusercontent.com/36637989/46462417-585a7300-c7b9-11e8-9030-ca954787db35.png)

**Comment by igormironchik** [comment]
Agree, without wordmark is better. I choose the second one, with dark background.
